services:

  postgres:
    image: postgres:15-alpine 
    environment:
      POSTGRES_DB: mydatabase          
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: mysecretpassword 
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  agreste-ingestor:    
    image: etidahouse/agreste-ingestor:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./wait-for-it:/usr/local/bin/wait-for-it
    entrypoint: ["bash", "/usr/local/bin/wait-for-it", "postgres:5432", "--", "/root/ingestor"]

  weather-ingestor:
    image: etidahouse/weather-ingestor:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
      API_URL: "https://api.openweathermap.org/data/2.5/weather"
      API_KEY: api_key
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ./wait-for-it:/usr/local/bin/wait-for-it
    entrypoint: ["bash", "/usr/local/bin/wait-for-it", "postgres:5432", "--", "/root/ingestor"]

  streamlit-app:
    image: etidahouse/streamlit-app:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
    depends_on:
      - postgres
    ports:
      - "8501:8501"


volumes:
  db_data:
